CREATE TABLE USUARIOS_SOPORTE_CABS (
    ID NUMBER NOT NULL,
    NUMERO_EMPLEADO VARCHAR2(10) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    PERMISOS NUMBER,
    ACTIVO NUMBER DEFAULT 0 NOT NULL,
    PERFIL VARCHAR2(20),
    CONSTRAINT USUARIOS_SOPORTE_CABS_PK PRIMARY KEY (ID) ENABLE 
);

INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, PERFIL) VALUES (1,'60054274', 'JOSE DANIEL HERNANDEZ OSORIO', 0, 'DESARROLLADOR WEB');
INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, PERFIL) VALUES (2,'60042774', 'ARTURO GARCIA GRACIA', 0, 'DESARROLLADOR');
INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, PERFIL) VALUES (3,'60054274', 'ERNESTO ESPINOZA PONCE', 0, 'DESARROLLADOR WEB');
INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, PERFIL) VALUES (4,'60053502', 'LIZETH GARCIA GAYOSSO', 0, 'DESARROLLADOR');
INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, PERFIL) VALUES (5,'60053925', 'JOSUE LEONEL MOTA SOLIS', 0, 'INGENIERO DE SOPORTE');
INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, PERFIL) VALUES (6,'60053717', 'LUIS MIGUEL GONZALEZ MIRANDA', 0, 'INGENIERO DE SOPORTE');
INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, PERFIL) VALUES (7,'60054274', 'JOSE DANIEL HERNANDEZ OSORIO', 0, 'DESARROLLADOR WEB');
INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, PERFIL) VALUES (8,'60054274', 'JOSE DANIEL HERNANDEZ OSORIO', 0, 'DESARROLLADOR WEB');
INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, PERFIL) VALUES (9,'60054274', 'JOSE DANIEL HERNANDEZ OSORIO', 0, 'DESARROLLADOR WEB');
INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, PERFIL) VALUES (10,'60054274', 'JOSE DANIEL HERNANDEZ OSORIO', 0, 'DESARROLLADOR WEB');
INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, PERFIL) VALUES (11,'60054274', 'JOSE DANIEL HERNANDEZ OSORIO', 0, 'DESARROLLADOR WEB');
INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, PERFIL) VALUES (12,'60054274', 'JOSE DANIEL HERNANDEZ OSORIO', 0, 'DESARROLLADOR WEB');
INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, PERFIL) VALUES (13,'60054274', 'JOSE DANIEL HERNANDEZ OSORIO', 0, 'DESARROLLADOR WEB');
INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, PERFIL) VALUES (14,'60054274', 'JOSE DANIEL HERNANDEZ OSORIO', 0, 'DESARROLLADOR WEB');
INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, PERFIL) VALUES (15,'60054274', 'JOSE DANIEL HERNANDEZ OSORIO', 0, 'DESARROLLADOR WEB');

DELETE FROM USUARIOS_SOPORTE_CABS WHERE ID > 0; 

SELECT NUMERO_EMPLEADO, NOMBRE, PERMISOS, ACTIVO, PERFIL FROM USUARIOS_SOPORTE_CABS WHERE NUMERO_EMPLEADO = '60054274';

INSERT INTO USUARIOS_SOPORTE_CABS(ID, NUMERO_EMPLEADO, NOMBRE, PERMISOS, ACTIVO, PERFIL) VALUES (1,'60054274', 'JOSE DANIEL HERNANDEZ OSORIO', 'SA', 1, 'DESARROLLADOR WEB');

DROP TABLE USUARIOS_SOPORTE_CABS;

CREATE TABLE CAT_OPER_INVENT_TESTIGOS(
    ID NUMBER NOT NULL,
    OPERACION VARCHAR2(20) NOT NULL,
    CONSTRAINT CAT_OPER_INVENT_TESTIGOS_PK PRIMARY KEY (ID) ENABLE 
);

INSERT INTO CAT_OPER_INVENT_TESTIGOS(ID,OPERACION) VALUES(1, 'INICIO DE SESION');
INSERT INTO CAT_OPER_INVENT_TESTIGOS(ID,OPERACION) VALUES(2, 'CIERRE DE SESION');
INSERT INTO CAT_OPER_INVENT_TESTIGOS(ID,OPERACION) VALUES(3, 'ERROR USUARIO');
INSERT INTO CAT_OPER_INVENT_TESTIGOS(ID,OPERACION) VALUES(4, 'ERROR CONTRASEÑA');
INSERT INTO CAT_OPER_INVENT_TESTIGOS(ID,OPERACION) VALUES(5, 'NO PRIVILEGIOS');
INSERT INTO CAT_OPER_INVENT_TESTIGOS(ID,OPERACION) VALUES(6, 'NO ACTIVO');
INSERT INTO CAT_OPER_INVENT_TESTIGOS(ID,OPERACION) VALUES(7, 'ACTUALIZACION');
INSERT INTO CAT_OPER_INVENT_TESTIGOS(ID,OPERACION) VALUES(8, 'INSERCION');

DROP TABLE CAT_OPER_INVENT_TESTIGOS;

CREATE TABLE CAT_NAVEGADOR_WEB(
    ID NUMBER NOT NULL,
    NAVEGADOR VARCHAR2(20) NOT NULL,
    CONSTRAINT CAT_NAVEGADOR_WEB_PK PRIMARY KEY (ID) ENABLE
);

INSERT INTO CAT_NAVEGADOR_WEB(ID,NAVEGADOR) VALUES(1, 'NO IDENTIFICADO');
INSERT INTO CAT_NAVEGADOR_WEB(ID,NAVEGADOR) VALUES(2, 'CHROME');
INSERT INTO CAT_NAVEGADOR_WEB(ID,NAVEGADOR) VALUES(3, 'FIREFOX');
INSERT INTO CAT_NAVEGADOR_WEB(ID,NAVEGADOR) VALUES(4, 'INTERNET EXPLORER');
INSERT INTO CAT_NAVEGADOR_WEB(ID,NAVEGADOR) VALUES(5, 'SAFARI');
INSERT INTO CAT_NAVEGADOR_WEB(ID,NAVEGADOR) VALUES(6, 'OPERA');

DELETE FROM CAT_NAVEGADOR_WEB WHERE ID > 0;

DROP TABLE CAT_NAVEGADOR_WEB;

CREATE TABLE CAT_SO_USUARIOS(
    ID NUMBER NOT NULL,
    SO VARCHAR2(15) NOT NULL,
    CONSTRAINT CAT_SO_USUARIOS_PK PRIMARY KEY (ID) ENABLE 
);

INSERT INTO CAT_SO_USUARIOS(ID,SO) VALUES(1, 'NO IDENTIFICADO');
INSERT INTO CAT_SO_USUARIOS(ID,SO) VALUES(2, 'WINDOWS 7');
INSERT INTO CAT_SO_USUARIOS(ID,SO) VALUES(3, 'WINDOWS 8');
INSERT INTO CAT_SO_USUARIOS(ID,SO) VALUES(4, 'WINDOWS 10');
INSERT INTO CAT_SO_USUARIOS(ID,SO) VALUES(5, 'WINDOWS SERVER');
INSERT INTO CAT_SO_USUARIOS(ID,SO) VALUES(6, 'LINUX UBUNTU');
INSERT INTO CAT_SO_USUARIOS(ID,SO) VALUES(7, 'LINUX DEBIAN');
INSERT INTO CAT_SO_USUARIOS(ID,SO) VALUES(8, 'MAC OS');

DELETE FROM CAT_SO_USUARIOS WHERE ID > 0;

DROP TABLE CAT_SO_USUARIOS;

CREATE TABLE BIT_INVENT_TESTIGOS (
    ID VARCHAR2(20) NOT NULL,
    FECHA DATE DEFAULT SYSDATE NOT NULL,
    OPERACION INT NOT NULL,
    IP VARCHAR2(20) NOT NULL,
    ID_USUARIO INT NOT NULL,
    NAVEGADOR INT NOT NULL,
    SO INT NOT NULL,
    DATOS VARCHAR2(300),
    CONSTRAINT BIT_INVENT_TESTIGOS_PK PRIMARY KEY (ID) ENABLE 
);

ALTER TABLE BIT_INVENT_TESTIGOS 
ADD CONSTRAINT BIT_INVENT_TESTIGOS_EMPLEADO_FK 
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS_SOPORTE_CABS;

ALTER TABLE BIT_INVENT_TESTIGOS 
ADD CONSTRAINT BIT_INVENT_TESTIGOS_OPERACION_FK 
FOREIGN KEY(OPERACION) REFERENCES CAT_OPER_INVENT_TESTIGOS; 

ALTER TABLE BIT_INVENT_TESTIGOS 
ADD CONSTRAINT BIT_INVENT_TESTIGOS_NAVEGADOR_FK 
FOREIGN KEY(NAVEGADOR) REFERENCES CAT_NAVEGADOR_WEB;

ALTER TABLE BIT_INVENT_TESTIGOS 
ADD CONSTRAINT BIT_INVENT_TESTIGOS_SO_FK 
FOREIGN KEY(SO) REFERENCES CAT_SO_USUARIOS; 

INSERT INTO BIT_INVENT_TESTIGOS(ID, OPERACION, IP, ID_USUARIO, NAVEGADOR, SO, DATOS) VALUES ('000504294025712', 1, '127.0.0.1', 1, 3, 6, '');

DROP TABLE BIT_INVENT_TESTIGOS;



SELECT REVISADOS FROM montest_concentrado_error WHERE id_test = 286 and fecha = 42921;
SELECT COUNT(REVISADO) FROM montest_detalle_error WHERE id_testigo = 286 and fecha = 42921;
